// AUTO-GENERATED by scripts/build-corpus.mjs — do not edit by hand.
// Statically imports every official-source page JSON so the corpus is bundled
// deterministically (no runtime filesystem access, works in tests and builds).
import type { OfficialSource } from "@/types";

import p0 from "../../../data/lemoore/pages/official-academic-calendar.json";
import p1 from "../../../data/lemoore/pages/official-admissions.json";
import p2 from "../../../data/lemoore/pages/official-cost-of-attendance.json";
import p3 from "../../../data/lemoore/pages/official-counseling.json";
import p4 from "../../../data/lemoore/pages/official-dsps.json";
import p5 from "../../../data/lemoore/pages/official-dual-enrollment.json";
import p6 from "../../../data/lemoore/pages/official-eops.json";
import p7 from "../../../data/lemoore/pages/official-financial-aid.json";
import p8 from "../../../data/lemoore/pages/official-graduation.json";
import p9 from "../../../data/lemoore/pages/official-library.json";
import p10 from "../../../data/lemoore/pages/official-registration.json";
import p11 from "../../../data/lemoore/pages/official-scholarships.json";
import p12 from "../../../data/lemoore/pages/official-student-portal.json";
import p13 from "../../../data/lemoore/pages/official-transcripts.json";
import p14 from "../../../data/lemoore/pages/official-tutoring.json";
import p15 from "../../../data/lemoore/pages/official-veterans.json";

export const OFFICIAL_PAGE_RECORDS: readonly OfficialSource[] = [
  p0,
  p1,
  p2,
  p3,
  p4,
  p5,
  p6,
  p7,
  p8,
  p9,
  p10,
  p11,
  p12,
  p13,
  p14,
  p15,
] as unknown as readonly OfficialSource[];
